In [ ]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris


In [1]:
# Load the Iris dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Features and target
X = df.drop('target', axis=1)
y = df['target']

df.head()


NameError: name 'load_iris' is not defined

In [ ]:
# Splitting the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [ ]:
# Standardizing features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [ ]:
# Initializing KNN with k=3
k = 3
knn = KNeighborsClassifier(n_neighbors=k)

# Train model
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=3)

In [ ]:
# Predictions
y_pred = knn.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")


Accuracy: 100.00%


In [ ]:
# Lists to store predictions
correct_preds = []
wrong_preds = []

for i in range(len(y_test)):
    if y_test.values[i] == y_pred[i]:
        correct_preds.append((i, y_test.values[i], y_pred[i]))
    else:
        wrong_preds.append((i, y_test.values[i], y_pred[i]))

print("\nCorrect Predictions:")
for i, actual, predicted in correct_preds:
    print(f"Index: {i}, Actual: {iris.target_names[actual]}, Predicted: {iris.target_names[predicted]}")

print("\nWrong Predictions:")
for i, actual, predicted in wrong_preds:
    print(f"Index: {i}, Actual: {iris.target_names[actual]}, Predicted: {iris.target_names[predicted]}")



Correct Predictions:
Index: 0, Actual: versicolor, Predicted: versicolor
Index: 1, Actual: setosa, Predicted: setosa
Index: 2, Actual: virginica, Predicted: virginica
Index: 3, Actual: versicolor, Predicted: versicolor
Index: 4, Actual: versicolor, Predicted: versicolor
Index: 5, Actual: setosa, Predicted: setosa
Index: 6, Actual: versicolor, Predicted: versicolor
Index: 7, Actual: virginica, Predicted: virginica
Index: 8, Actual: versicolor, Predicted: versicolor
Index: 9, Actual: versicolor, Predicted: versicolor
Index: 10, Actual: virginica, Predicted: virginica
Index: 11, Actual: setosa, Predicted: setosa
Index: 12, Actual: setosa, Predicted: setosa
Index: 13, Actual: setosa, Predicted: setosa
Index: 14, Actual: setosa, Predicted: setosa
Index: 15, Actual: versicolor, Predicted: versicolor
Index: 16, Actual: virginica, Predicted: virginica
Index: 17, Actual: versicolor, Predicted: versicolor
Index: 18, Actual: versicolor, Predicted: versicolor
Index: 19, Actual: virginica, Predict

In [ ]:
# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)



Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
