### Covariance and Correlation and their Matrices

In [1]:
import numpy as np
import pandas as pd

In [4]:
# Function to calculate covariance
def calculate_covariance(X, Y): 
    mean_X = np.mean(X)
    mean_Y = np.mean(Y)
    covariance = np.mean((X - mean_X) * (Y - mean_Y))
    return covariance

In [21]:
# Function to calculate correlation
def calculate_correlation(X, Y):
    covariance = calculate_covariance(X, Y)
    std_X = np.std(X)
    std_Y = np.std(Y)
    correlation = covariance / (std_X * std_Y)
    return correlation

In [11]:
# Function to compute covariancematrix
def covariance_matrix(data):
    return np.cov(data, rowvar=False)

In [12]:
# Function to compute correlation matrix
def correlation_matrix(data):
    return np.corrcoef(data, rowvar=False)

In [14]:
# Sample dataset
data = {
'X': [1, 2, 3, 4, 5],
'Y': [2, 4, 6, 8, 10],
'Z': [5, 4, 3, 2, 1]
}

In [15]:
# Convert to pandas DataFrame
df = pd.DataFrame(data)

In [22]:
# Compute covariance and correlation between 'X' and 'Y' 
cov_xy = calculate_covariance(df['X'],df['Y'])
cor_xy = calculate_correlation(df['X'], df['Y'])

In [17]:
# Compute covariance matrix and correlation matrix
cov_matrix = covariance_matrix(df)
corr_matrix = correlation_matrix(df)

In [24]:
print("Covariance between X and Y:", cov_xy) 
print("Correlation between X and Y:", cor_xy)

Covariance between X and Y: 4.0
Correlation between X and Y: 0.9999999999999998


In [19]:
print("Covariance Matrix:\n", cov_matrix) 
print("Correlation Matrix:\n", corr_matrix)

Covariance Matrix:
 [[ 2.5  5.  -2.5]
 [ 5.  10.  -5. ]
 [-2.5 -5.   2.5]]
Correlation Matrix:
 [[ 1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]]
